# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Simple local RAG index for Siemens Teamcenter sample knowledge."""

from __future__ import annotations

import hashlib
import json
import math
from dataclasses import dataclass
from pathlib import Path

DOCS_PATH = Path(__file__).parent / "data" / "seed_siemens_docs.json"
VECTOR_DIM = 128


@dataclass(frozen=True)
class IndexedDoc:
  """Container for a Teamcenter document and precomputed vector."""

  doc_id: str
  role: str
  source: str
  content: str
  vector: list[float]


def _normalize(vector: list[float]) -> list[float]:
  mag = math.sqrt(sum(x * x for x in vector))
  if mag == 0:
    return vector
  return [x / mag for x in vector]


def embed_text(text: str, dim: int = VECTOR_DIM) -> list[float]:
  """Create deterministic sample embeddings for offline demos.

  The vector is generated by hashing tokens into a fixed-size vector.
  This is intentionally lightweight so the sample works without GPU or
  external embedding APIs.
  """
  vector = [0.0] * dim
  for token in text.lower().split():
    digest = hashlib.sha256(token.encode("utf-8")).digest()
    bucket = int.from_bytes(digest[:2], "big") % dim
    sign = 1.0 if digest[2] % 2 == 0 else -1.0
    vector[bucket] += sign
  return _normalize(vector)


def load_docs(path: Path = DOCS_PATH) -> list[dict[str, str]]:
  with path.open("r", encoding="utf-8") as f:
    return json.load(f)


def build_index(path: Path = DOCS_PATH) -> list[IndexedDoc]:
  docs = load_docs(path)
  return [
      IndexedDoc(
          doc_id=doc["doc_id"],
          role=doc["role"],
          source=doc["source"],
          content=doc["content"],
          vector=embed_text(doc["content"]),
      )
      for doc in docs
  ]


def search(query: str, top_k: int = 3) -> list[IndexedDoc]:
  q_vec = embed_text(query)
  scored: list[tuple[float, IndexedDoc]] = []
  for entry in build_index():
    score = sum(a * b for a, b in zip(q_vec, entry.vector))
    scored.append((score, entry))
  scored.sort(key=lambda item: item[0], reverse=True)
  return [item[1] for item in scored[:top_k]]


def retrieve_teamcenter_knowledge(question: str, role: str = "general") -> str:
  """RAG tool for all agents: returns role-aware contextual snippets."""
  retrieved = search(f"{role} {question}")
  lines = []
  for doc in retrieved:
    lines.append(
        f"[{doc.doc_id}] role={doc.role} source={doc.source}: {doc.content}"
    )
  return "\n".join(lines)
